stages:

  data_load:
    cmd: python src/stages/data_load.py --config=params.yaml
    deps:
    - src/stages/data_load.py
    params:
    - base
    - data_load
    outs:
    - data/

  train:
    cmd: python src/stages/train.py --config=params.yaml
    deps:
    - src/stages/train.py
    - data/
    params:
    - base
    - train
    outs:
    - models/

  evaluate:
    cmd: python src/stages/evaluate.py --config=params.yaml
    deps:
    - src/stages/evaluate.py
    - models/
    - data/
    params:
    - base
    - evaluate
    outs:
    - reports/
