
base:
  random_state: 42
  log_level: INFO
  mlflow_experiment_name: classification


data_load:
  dataset_url: 'https://download.pytorch.org/tutorial/hymenoptera_data.zip'
  dataset_filename: 'hymenoptera_data.zip'
  dataset_folder: 'data/hymenoptera_data'


train:
  base_model_name: resnet18
  base_model_trainable: false
  num_epochs: 1
  optim_name: SGD
  optim:
    SGD:
      lr: 0.001
      momentum: 0.9
  lrs_name: StepLR
  lrs:
    StepLR:
      step_size: 7
      gamma: 0.1
  model_path: models/model.pt


evaluate:
  reports_dir: reports
  metrics_file: 'metrics.json'
  confusion_matrix_image: 'confusion_matrix.png'
