name: dvc repro

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'

jobs:
  train-and-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Train model
        run: |
          pip install -r requirements.txt
          dvc repro
